INSERT INTO PORTAL.TOPIC (TITLE, DESCRIPTION, HITS, ID, COURSE_ID) VALUES ('Linked List', 'In computer science, a linked list is a linear collection of data elements, called nodes, each pointing to the next node by means of a pointer. It is a data structure consisting of a group of nodes which together represent a sequence.', null, 1, 1);
INSERT INTO PORTAL.TOPIC (TITLE, DESCRIPTION, HITS, ID, COURSE_ID) VALUES ('Heap', 'In computer science, a heap is a specialized tree-based data structure that satisfies the heap property: If A is a parent node of B, then the key (the value) of node A is ordered with respect to the key of node B with the same ordering applying across the heap.', null, 2, 1);
INSERT INTO PORTAL.TOPIC (TITLE, DESCRIPTION, HITS, ID, COURSE_ID) VALUES ('Hash Dictionary', 'Hash Table is a data structure which stores data in an associative manner. In a hash table, data is stored in an array format, where each data value has its own unique index value. Access of data becomes very fast if we know the index of the desired data.', null, 3, 1);
INSERT INTO PORTAL.TOPIC (TITLE, DESCRIPTION, HITS, ID, COURSE_ID) VALUES ('Relational Schema', 'Before you can define the database tables using a specific database management software and DDL (Data Definition Language), you must write a relation shema for each table. The set of relation schemas form the relational database schema which is used as input when defining the database.', null, 4, 2);
INSERT INTO PORTAL.TOPIC (TITLE, DESCRIPTION, HITS, ID, COURSE_ID) VALUES ('ER Diagram', 'An entity relationship diagram (ERD) shows the relationships of entity sets stored in a database. An entity in this context is a component of data. In other words, ER diagrams illustrate the logical structure of databases.', null, 5, 2);
INSERT INTO PORTAL.TOPIC (TITLE, DESCRIPTION, HITS, ID, COURSE_ID) VALUES ('Normalization', 'Normalization is a systematic approach of decomposing tables to eliminate data redundancy and undesirable characteristics like Insertion, Update and Deletion Anamolies. It is a multi-step process that puts data into tabular form by removing duplicated data from the relation tables.', null, 6, 2);
INSERT INTO PORTAL.TOPIC (TITLE, DESCRIPTION, HITS, ID, COURSE_ID) VALUES ('Abstraction', 'Abstraction is the process of abstraction in Java is used to hide certain details and only show the essential features of the object. In other words, it deals with the outside view of an object (interface). Now this is the part which confuses me always.', null, 7, 3);
INSERT INTO PORTAL.TOPIC (TITLE, DESCRIPTION, HITS, ID, COURSE_ID) VALUES ('Inheritance', 'The extends keyword indicates that you are making a new class that derives from an existing class. The meaning of "extends" is to increase the functionality. In the terminology of Java, a class which is inherited is called parent or super class and the new class is called child or subclass.', null, 8, 3);
INSERT INTO PORTAL.TOPIC (TITLE, DESCRIPTION, HITS, ID, COURSE_ID) VALUES ('Polymorphism', 'Polymorphism is the ability of an object to take on many forms. The most common use of polymorphism in OOP occurs when a parent class reference is used to refer to a child class object. Any Java object that can pass more than one IS-A test is considered to be polymorphic', null, 9, 3);
INSERT INTO PORTAL.TOPIC (TITLE, DESCRIPTION, HITS, ID, COURSE_ID) VALUES ('Abstraction', 'Encapsulation is used to hide its members from outside class or interface, whereas abstraction is used to show only essential features. In C# programming, Encapsulation uses five types of modifier to encapsulate data. These modifiers are public, private, internal, protected and protected internal.', null, 10, 4);
INSERT INTO PORTAL.TOPIC (TITLE, DESCRIPTION, HITS, ID, COURSE_ID) VALUES ('Inheritance', 'Inheritance is the ability to create a class from another class, the "parent" class, extending the functionality and state of the parent in the derived, or "child" class. It allows derived classes to overload methods from their parent class. Inheritance is one of the pillars of object-orientation.', null, 11, 4);
INSERT INTO PORTAL.TOPIC (TITLE, DESCRIPTION, HITS, ID, COURSE_ID) VALUES ('Polymorphism', 'The word polymorphism means having many forms. In object-oriented programming paradigm, polymorphism is often expressed as ''one interface, multiple functions''. Polymorphism can be static or dynamic. In static polymorphism, the response to a function is determined at the compile time.', null, 12, 4);
INSERT INTO PORTAL.TOPIC (TITLE, DESCRIPTION, HITS, ID, COURSE_ID) VALUES ('Conversion', 'There are many methods or techniques which can be used to convert numbers from one base to another. We''ll demonstrate here the following -

Decimal to Other Base System
Other Base System to Decimal
Other Base System to Non-Decimal
Shortcut method - Binary to Octal
Shortcut method - Octal to Binary
Shortcut method - Binary to Hexadecimal
Shortcut method - Hexadecimal to Binary', null, 13, 5);
INSERT INTO PORTAL.TOPIC (TITLE, DESCRIPTION, HITS, ID, COURSE_ID) VALUES ('Stack', 'Assembly languages provide you the ability to implement conditional statements. If you add and jump/branches (the assembly equivalent of "goto" statements), you can implement loops.
The next step is some kind of support for functions. Functions are perhaps the most fundamental language feature for abstraction and code reuse. It allows us to refer to some piece of code by a name.', null, 14, 5);
INSERT INTO PORTAL.TOPIC (TITLE, DESCRIPTION, HITS, ID, COURSE_ID) VALUES ('Shift and Rotate', '   Shift instructions move a bit string (or operand treated as a bit string) to the right or left, with excess bits discarded (although one or more bits might be preserved in flags).Rotate instructions are similar to shift instructions, ecept that rotate instructions are circular, with the bits shifted out one end returning on the other end. Rotates can be to the left or right. Rotates can also employ an extend bit for multi-precision rotates.', null, 15, 5);