INSERT INTO PORTAL.ANSWER (TITLE, DESCRIPTION, RATING, ID, MEMBER_ID, QUESTION_ID) VALUES ('null', 'Both... lol', 0, 5, '16-1', 1);
INSERT INTO PORTAL.ANSWER (TITLE, DESCRIPTION, RATING, ID, MEMBER_ID, QUESTION_ID) VALUES ('null', 'they have different implementations bro.', 0, 6, '16-1', 1);
INSERT INTO PORTAL.ANSWER (TITLE, DESCRIPTION, RATING, ID, MEMBER_ID, QUESTION_ID) VALUES ('null', 'Bubble Sort is the easiest way..!', 0, 1, '16-1', 4);
INSERT INTO PORTAL.ANSWER (TITLE, DESCRIPTION, RATING, ID, MEMBER_ID, QUESTION_ID) VALUES ('null', 'Selection Sort..!', 0, 2, '2017-3', 4);
INSERT INTO PORTAL.ANSWER (TITLE, DESCRIPTION, RATING, ID, MEMBER_ID, QUESTION_ID) VALUES ('null', 'Security purpose. Restricted access.', 0, 3, '16-1', 2);
INSERT INTO PORTAL.ANSWER (TITLE, DESCRIPTION, RATING, ID, MEMBER_ID, QUESTION_ID) VALUES ('null', 'Google it', 0, 4, '16-1', 10);